// Generated by CoffeeScript 1.7.1
define(function(require) {
	return function(app) {
		app.run([ '$rootScope','Announcement', 'Demand','$timeout', '$http',
				function($rootScope,Announcement,Demand, $timeout, $http) {
					if (!sessionStorage.length || !sessionStorage.logName || !sessionStorage.id) {//
						alert('用户信息已失效,请您重新登录系统!')
						location.href = 'login.html';
					}
					
					//查看公告详细信息
					$rootScope.toDetail = function(announcement){
		        		$rootScope.announcement = angular.copy(announcement) || new Announcement;
		        		
		        	};
		        	
		        	//查看代办任务详情
		        	$rootScope.toSeeDetail = function(demand){
		        		//不跨级申请
		        		//成果确认
		        		if(demand.approState=='6'){
		        			location.href = '#/at/technologicalProcess/achievement/result?id=' + demand.id;
		        		//需求申请
		        		}else if (demand.approState=='1'){
		        			location.href = '#/at/technologicalProcess/demandManage/req?id=' + demand.id;
		        		//业务领导需求审核
		        		}else if (demand.approState=='2'){
		        			location.href = '#/at/technologicalProcess/demandManage/eap?id=' + demand.id;
		        		//需求列表
		        		}else if (demand.approState=='3'){
		        			location.href = '#/at/technologicalProcess/demandManage/list?id=' + demand.id;
		        		//技术领导审核
		        		}else if (demand.approState=='4'){
		        			location.href = '#/at/technologicalProcess/demandManage/eap?id=' + demand.id;
		        		//待技术员确认
		        		}else if (demand.approState=='5'){
		        			location.href = '#/at/technologicalProcess/demandManage/affirm?id=' + demand.id;
		        		}
		        		
		        		//跨机构申请
		        		//需求审核
		        		else if (demand.approState=='9'){
		        			location.href = '#/at/technologicalProcess/demandManage/eap?id=' + demand.id;
		        		//需求列表
		        		}else if (demand.approState=='a' || demand.approState=='b' ){
		        			location.href = '#/at/technologicalProcess/demandManage/list?id=' + demand.id;
		        		//需求审核
		        		}else if (demand.approState=='c'){
		        			location.href = '#/at/technologicalProcess/demandManage/eap?id=' + demand.id;
		        		//需求确认
		        		}else if (demand.approState=='d'){
		        			location.href = '#/at/technologicalProcess/demandManage/affirm?id=' + demand.id;
		        		//成果确认
		        		}else if (demand.approState=='e'){
		        			location.href = '#/at/technologicalProcess/achievement/result?id=' + demand.id;
		        		}
		        		
		        		//技术申请
		        		//需求申请
		        		else if (demand.approState=='f'){
		        			location.href = '#/at/technologicalProcess/demandManage/eap?id=' + demand.id;
		        		//需求确认
		        		}else if (demand.approState=='g'){
		        			location.href = '#/at/technologicalProcess/demandManage/affirm?id=' + demand.id;
		        		//成果确认
		        		}else if (demand.approState=='h'){
		        			location.href = '#/at/technologicalProcess/achievement/result?id=' + demand.id;
		        		}
               		}
		        	
		        	//查看公告
		        	Announcement.query({isArray : true,params:{
							annoState:2
						}}, function(list){
							$rootScope.announceNumber = list.length;
							$rootScope.announceList = list;
					});
		        	
		        	
		        	

		        	
		        	
                    //报表地址
                    $rootScope.resultPath = seajs.data.data.resultPath;

					$rootScope.USER_INFO = angular.copy(sessionStorage);//

					$rootScope.USER_INFO.institution = angular.fromJson($rootScope.USER_INFO.institution) || {};
					
					$rootScope.logout = function() {//
						
						$http({
							method : 'post',
							url : 'auth.shtml',
							data : {
								logout : true
							}
						}).success(function(result) {
							
							if (result.success === "false") {
								alert(result.message)
							} else {
								sessionStorage.clear();
								$timeout(function() {
									location.href = 'login.html';
								}, 1);
							}
						});

					};
				} ]);
		app.controller('RePasswordCtrl', [ '$scope','User', function($scope,User) {
				$scope.user = new User($scope.USER_INFO);
				$scope.send = function(){
					User.post({
						pwd:true,
						userId:$scope.user.id,
						oldPwd:$scope.oldpwd,
						newPwd:$scope.newpwd
					},function(result){
						if(result.success==='false'){
							alert(result.message);
						}else{
							alert('密码已修改，请重新登录!');
							$scope.logout();
						}
					});
				}
		} ]);

		app.controller('UpdateUserCtrl', [ '$scope','$rootScope','User',  function($scope,$rootScope,User) {
				var tmp = $scope.USER_INFO;
				$scope.user = new User({
					id : tmp.id,
					userName : tmp.userName,
					email : tmp.email,
					phone : tmp.phone
				});
				$scope.updateUser=function(){
					User.save($scope.user, function(result){
						if(result.success === 'false'){
							alert(result.message);
						}else{
							alert('个人信息修改成功!');
		    				sessionStorage.userName = $scope.user.userName;
		    				sessionStorage.email = $scope.user.email;
		    				sessionStorage.phone = $scope.user.phone;
		    				$rootScope.USER_INFO = angular.copy(sessionStorage);//
						}
					})
				}
		} ]);
	}
});
