// Generated by CoffeeScript 1.7.1
define(function(require) {
  var app, loginBoxCtrl;
  require('base');
  app = angular.module('app', ['base']);
  loginBoxCtrl = ['$scope' , '$http' , '$timeout' , function($scope , $http, $timeout) {
	  
	  $scope.userName='admin'|| $scope.userName;
	  $scope.password='123'||$scope.password;
	  
	  
    $scope.login = function() {
    	$http({
    		method : 'post',
    		url : 'auth.shtml',
    		data : {auth:true,userName : $scope.userName , password:$scope.password}
    	}).success(function(result){
    		
    		if(result && result.success === "true"){
    			angular.forEach(result.userInfo , function(value , key){
    				sessionStorage[key] = angular.isObject(value) ? angular.toJson(value) : value;
    			});
    			//
    			sessionStorage.contextPath=result.contextPath;
    			$timeout(function(){
    				location.href = "index.html#/at/index";		
    			} , 1);
    		}else if(result && result.success === "false"){
                alert(result.message);
            }
    	});
    };
  }];
  app.controller('login-box', loginBoxCtrl);
  angular.bootstrap(document, ['app']);
});
