Ext.namespace("Free");
Free.sale_plan='<table><tr><td id="sale_plan_0" colspan="4" valign="top"></td><td id="sale_plan_1" rowspan="2" valign="middle"></td></tr><tr><td id="sale_plan_2"></td><td id="sale_plan_3"></td><td id="sale_plan_4"></td><td id="sale_plan_5"></td></tr><td id="sale_plan_6" colspan="5" valign="top"></td></table>';
Free.stock_index='<table><tr><td id="stock_index_0" colspan="3" valign="top"></td></tr><tr><td id="stock_index_1"></td><td id="stock_index_2"></td><td id="stock_index_3"></td></tr><tr><td  colspan="3"><div style="height:7px;margin-top:5px;BORDER-TOP:#B3DAF8 1px solid;"></div></td></tr><tr><td id="stock_index_4"></td><td id="stock_index_5" colspan="3" valign="top"></td></tr><td id="stock_index_6" colspan="4" valign="top"></td></table>'
Free.subject_index='<table><tr><td id="subject_index_0"></td><td id="subject_index_1" colspan="2"></td><td id="subject_index_2" colspan="2"></td></tr><tr><td id="subject_index_3"></td><td id="subject_index_4" rowspan="3"></td><td id="subject_index_5" rowspan="3"></td><td id="subject_index_6" rowspan="3"></td><td id="subject_index_7" rowspan="3"></td></tr><tr><td id="subject_index_8"></td></tr><tr><td id="subject_index_9"></td></tr><tr><td  colspan="5"><div style="height:7px;margin-top:5px;BORDER-TOP:#B3DAF8 1px solid;"></div></td></tr><tr><td id="subject_index_10" colspan="2"></td><td id="subject_index_11" colspan="3" ></td></tr><tr><td id="subject_index_12" colspan="2"></td><td id="subject_index_13" colspan="3"></td></tr></table>';
Free.sub_index='<table><tr><td id="sub_index_0"></td><td id="sub_index_1" colspan="2"></td><td id="sub_index_2" colspan="2"></td></tr><tr><td id="sub_index_3"></td><td id="sub_index_4" rowspan="3"></td><td id="sub_index_5" rowspan="3"></td><td id="sub_index_6" rowspan="3"></td><td id="sub_index_7" rowspan="3"></td></tr><tr><td id="sub_index_8"></td></tr><tr><td id="sub_index_9"></td></tr></table>';
Free.hrDeploy3 = '<table><tr><td id="hrDeploy3_0"></td><td id="hrDeploy3_1"></td><td id="hrDeploy3_2"></td><td id="hrDeploy3_3"></td><td id="hrDeploy3_4"></td><td id="hrDeploy3_5"></td></tr></table>';
Free.sale_p='<table ><tr><td id="sale_p_0" colspan="4" valign="top"></td><td id="sale_p_1" rowspan="2" valign="top"></td></tr><tr><td id="sale_p_2"></td><td id="sale_p_3"></td><td id="sale_p_4"></td><td id="sale_p_5"></td></tr><tr><td  colspan="5"><div style="height:7px;margin-top:5px;BORDER-TOP:#B3DAF8 1px solid;"></div></td></tr><tr><td id="sale_p_6" colspan="5" valign="top"></td></tr><tr><td id="sale_p_7" colspan="3" valign="top"></td><td id="sale_p_8" colspan="2" valign="top"></td></tr><tr><td id="sale_p_9" colspan="5" valign="top"></td></tr></table>';
Free.dasp1 = '<table ><tr><td id="dasp1_0" align="middle" ></td><td id="dasp1_1"align="left" ></td><td id="dasp1_2" align="left"></td></tr><tr ><td id="dasp1_3" colspan="4"  align="middle"></td></tr><tr ><td colspan="4" ><div style="height:1px;background-color:#B3DAF8;font-size:1px;line-height:0;overflow:hidden;top:5px;"></div></td>  </tr><tr><td id="dasp1_4" rowspan="2" ></td><td id="dasp1_5" colspan="2"></td>  </tr>  <tr >    <td id="dasp1_6" colspan="2"></td>  </tr>  <tr ><td colspan="4" ><div style="height:1px;background-color:#B3DAF8;font-size:1px;line-height:0;overflow:hidden;top:5px;"></div></td></tr><tr ><td id="dasp1_7" colspan="2" ></td><td id="dasp1_8"></td></tr></table>';
Free.dasp2='<table style="text-align:center;overflow:auto;margin:0 auto;"><tr><td id="dasp2_10" colspan="4"></td></tr>  <tr >    <td id="dasp2_0" ></td>  <td id="dasp2_1"></td>	<td id="dasp2_2"  rowspan="2"></td>	<td id="dasp2_3" rowspan="2"></td>  </tr>    <tr > <td id="dasp2_4" colspan="2"></td>  </tr>      <tr>    	<td id="dasp2_5" colspan="2" rowspan="2"></td> 	<td id="dasp2_6" colspan="2" ></td>   </tr>        <tr>    	<td id="dasp2_7" colspan="2"></td>   </tr>    <tr >    <td colspan="4" ><div style="height:1px;background-color:#B3DAF8;font-size:1px;line-height:0;overflow:hidden;top:5px;"></div></td>  </tr>      <tr>    <td id="dasp2_8" colspan="2"></td>	<td id="dasp2_9" colspan="2"></td>	  </tr></table>';
Free.bkyw='<table style="text-align:center;overflow:auto;margin:0 auto;"> <tr > <td id="bkyw_0" colspan="2"></td>  </tr> <tr > <td id="bkyw_1" ></td> <td id="bkyw_2"></td>  </tr>    <tr > <td id="bkyw_3" colspan="2"></td>  </tr>  </table>';
Free.manage1='<table style="text-align:center;overflow:auto;margin:0 auto;"> <tr >   <td id="manage1_0" colspan="3"></td> </tr> <tr><td id="manage1_1" ></td>    <td id="manage1_2"></td>        <td id="manage1_3"  ></td>  </tr>    <tr >    <td id="manage1_4" colspan="2"></td>	<td id="manage1_5" colspan="2"></td>  </tr></table>';
Free.cross='<table style="text-align:center;overflow:auto;margin:0 auto;"><tr> <td id="cross_0" colspan=3></td><tr >  <tr >    <td id="cross_1" ></td>    <td id="cross_2"></td> </tr>    <tr >	 <td id="cross_3"  ></td>    <td id="cross_4" ></td>  </tr></table>';